export enum TableName {
    LOGGER = 'loggers',
    ORDER_COUPON = 'order_coupon',
    ORDER_PRODUCT = 'order_products',
    WISHLIST = 'wishlist',
    unit_master = 'unit_master',
    USER_ADDRESS = 'user_addresses',
    USER = 'users',
    BRAND = 'brands',
    TAG_MASTER = "tag_master",
    CATEGORIES = 'categories',
    STATE_MASTER = 'state_master',
    CITY = "city_master",
    COUPON = 'coupons',
    PIN_CODE_MASTER = 'pincode_master',
    TEMPLATE = 'templates',
    ORDER = 'orders',
    COMMENT = 'Comment',
    CART = 'cart',
    ENQUIRY = 'enquires',
    ORDER_ADDRESS = 'order_address',
    ORDER_STATUS = 'order_statuses',
    BANNER = 'banners',
    PRODUCT_IMAGES = 'product_images',
    PRODUCT = 'products',
    AUTH = "auths",
    EMAIL_HISTORY = "email_history",
    ORDER_HISTORY = "order_history",
}

